import requests
import os
from urllib.parse import urlparse, unquote

def download_image(url, folder_path):
    # Clean the URL by removing escaped slashes
    url = url.replace('/', '/')
    
    # Skip if URL is not a valid http/https URL or if it's a placeholder
    if not url.startswith(('http://', 'https://')) or url in ['PLAYER', '00']:
        return
    
    try:
        # Get the filename from the URL and decode any URL encoding
        filename = unquote(os.path.basename(urlparse(url).path))
        
        # Create full path
        full_path = os.path.join(folder_path, filename)
        
        # Skip if file already exists
        if os.path.exists(full_path):
            print(f"File already exists: {filename}")
            return
        
        # Download the image
        response = requests.get(url)
        response.raise_for_status()  # Raise an exception for bad status codes
        
        # Save the image
        with open(full_path, 'wb') as f:
            f.write(response.content)
        
        print(f"Successfully downloaded: {filename}")
        
    except Exception as e:
        print(f"Error downloading {url}: {str(e)}")

def extract_image_urls(data):
    urls = set()
    
    # Get product thumbnail and main thumbnail
    if 'productThumbnail' in data:
        urls.add(data['productThumbnail'])
    if 'thumbnail' in data:
        urls.add(data['thumbnail'])
    
    # Get images from elements
    for element in data.get('elements', []):
        if 'source' in element and isinstance(element['source'], str):
            if element['source'].startswith(('http://', 'https://')):
                urls.add(element['source'])
    
    return urls

def main():
    # Create downloads directory
    download_dir = 'jersix_levels_images'
    os.makedirs(download_dir, exist_ok=True)
    
    # Extract image URLs
    image_urls = extract_image_urls(data)
    
    # Download each image
    print(f"Found {len(image_urls)} unique images to download")
    for url in image_urls:
        download_image(url, download_dir)

# Your JSON data
data = {
                    "productTitle": "Kit Evolution - LEVELS",
                    "productThumbnail": "http://jersix.com/en/wp-content/uploads/2022/08/levels-kit-evolution-p.png",
                    "title": "View 1",
                    "thumbnail": "https://jersix.com/en/wp-content/uploads/2019/11/completo-kit-calcio-classic.jpg",
                    "options": {
                        "stageWidth": 1400,
                        "stageHeight": 1200,
                        "customAdds": {
                            "uploads": True,
                            "texts": True,
                            "designs": True
                        }
                    },
                    "elements": [
                        {
                            "title": "Color 1",
                            "source": "https://jersix.com/en/wp-content/uploads/2022/06/kit-ev-m-BASE.png",
                            "type": "image",
                            "parameters": {
                                "left": 700,
                                "top": 600,
                                "originX": "center",
                                "originY": "center",
                                "z": -1,
                                "fill": "#dcddde",
                                "colorLinkGroup": False,
                                "draggable": False,
                                "rotatable": False,
                                "resizable": False,
                                "removable": False,
                                "flipX": False,
                                "flipY": False,
                                "zChangeable": False,
                                "scaleX": 0.98,
                                "scaleY": 0.98,
                                "uniScalingUnlockable": False,
                                "angle": 0,
                                "price": 0,
                                "autoCenter": False,
                                "replaceInAllViews": False,
                                "autoSelect": False,
                                "topped": False,
                                "boundingBoxMode": "0",
                                "opacity": 1,
                                "excludeFromExport": False,
                                "locked": False,
                                "showInColorSelection": False,
                                "boundingBox": "",
                                "fixed": False,
                                "resizeToW": "0",
                                "resizeToH": "0",
                                "scaleMode": "0",
                                "minScaleLimit": 0.01,
                                "advancedEditing": False,
                                "uploadZone": False,
                                "uploadZoneMovable": False,
                                "uploadZoneRemovable": False,
                                "pattern": "",
                                "customAdds": [],
                                "colors": "#FFFFFF,#0A0A0A,#232323,#555555,#B2B2B2,#CDCDCD,#412623,#4E1616,#800707,#BA0909,#D55108,#E88014,#E29717,#FDC300,#FFED00,#646702,#042E21,#05462B,#026C27,#489A29,#A4CB16,#191F28,#172339,#0A376E,#005A96,#08A1BB,#8DEAF4,#08ADB1,#3DD684,#92EFBD,#234955,#2E2846,#402E54,#736D88,#BDB7CF,#56182F,#761133,#A60E32,#D83636,#F591A7,#F2C5AD,#F8E9E8,#381F0E,#583116,#AA650F,#6F3827,#C7932E"
                            }
                        },
                        {
                            "title": "Color 2 (Sleeves)",
                            "source": "https://jersix.com/en/wp-content/uploads/2022/06/kit-ev-m-SLEEVES.png",
                            "type": "image",
                            "parameters": {
                                "left": 700,
                                "top": 600,
                                "originX": "center",
                                "originY": "center",
                                "z": -1,
                                "fill": "#dcddde",
                                "colorLinkGroup": False,
                                "draggable": False,
                                "rotatable": False,
                                "resizable": False,
                                "removable": False,
                                "flipX": False,
                                "flipY": False,
                                "zChangeable": False,
                                "scaleX": 0.98,
                                "scaleY": 0.98,
                                "uniScalingUnlockable": False,
                                "angle": 0,
                                "price": 0,
                                "autoCenter": False,
                                "replaceInAllViews": False,
                                "autoSelect": False,
                                "topped": False,
                                "boundingBoxMode": "0",
                                "opacity": 1,
                                "excludeFromExport": False,
                                "locked": False,
                                "showInColorSelection": False,
                                "boundingBox": "",
                                "fixed": False,
                                "resizeToW": "0",
                                "resizeToH": "0",
                                "scaleMode": "0",
                                "minScaleLimit": 0.01,
                                "advancedEditing": False,
                                "uploadZone": False,
                                "uploadZoneMovable": False,
                                "uploadZoneRemovable": False,
                                "customAdds": [],
                                "colors": "#FFFFFF,#0A0A0A,#232323,#555555,#B2B2B2,#CDCDCD,#412623,#4E1616,#800707,#BA0909,#D55108,#E88014,#E29717,#FDC300,#FFED00,#646702,#042E21,#05462B,#026C27,#489A29,#A4CB16,#191F28,#172339,#0A376E,#005A96,#08A1BB,#8DEAF4,#08ADB1,#3DD684,#92EFBD,#234955,#2E2846,#402E54,#736D88,#BDB7CF,#56182F,#761133,#A60E32,#D83636,#F591A7,#F2C5AD,#F8E9E8,#381F0E,#583116,#AA650F,#6F3827,#C7932E"
                            }
                        },
                        {
                            "title": "Color 3 (Shorts)",
                            "source": "https://jersix.com/en/wp-content/uploads/2022/06/kit-ev-m-SHORTS.png",
                            "type": "image",
                            "parameters": {
                                "left": 700,
                                "top": 600,
                                "originX": "center",
                                "originY": "center",
                                "z": -1,
                                "fill": "#dcddde",
                                "colorLinkGroup": False,
                                "draggable": False,
                                "rotatable": False,
                                "resizable": False,
                                "removable": False,
                                "flipX": False,
                                "flipY": False,
                                "zChangeable": False,
                                "scaleX": 0.98,
                                "scaleY": 0.98,
                                "uniScalingUnlockable": False,
                                "angle": 0,
                                "price": 0,
                                "autoCenter": False,
                                "replaceInAllViews": False,
                                "autoSelect": False,
                                "topped": False,
                                "boundingBoxMode": "0",
                                "opacity": 1,
                                "excludeFromExport": False,
                                "locked": False,
                                "showInColorSelection": False,
                                "boundingBox": "",
                                "fixed": False,
                                "resizeToW": "0",
                                "resizeToH": "0",
                                "scaleMode": "0",
                                "minScaleLimit": 0.01,
                                "advancedEditing": False,
                                "uploadZone": False,
                                "uploadZoneMovable": False,
                                "uploadZoneRemovable": False,
                                "customAdds": [],
                                "colors": "#FFFFFF,#0A0A0A,#232323,#555555,#B2B2B2,#CDCDCD,#412623,#4E1616,#800707,#BA0909,#D55108,#E88014,#E29717,#FDC300,#FFED00,#646702,#042E21,#05462B,#026C27,#489A29,#A4CB16,#191F28,#172339,#0A376E,#005A96,#08A1BB,#8DEAF4,#08ADB1,#3DD684,#92EFBD,#234955,#2E2846,#402E54,#736D88,#BDB7CF,#56182F,#761133,#A60E32,#D83636,#F591A7,#F2C5AD,#F8E9E8,#381F0E,#583116,#AA650F,#6F3827,#C7932E"
                            }
                        },
                        {
                            "title": "Color 4",
                            "source": "https://jersix.com/en/wp-content/uploads/2022/08/levels-kit-evolution-c1.png",
                            "type": "image",
                            "parameters": {
                                "left": 700,
                                "top": 600,
                                "originX": "center",
                                "originY": "center",
                                "z": -1,
                                "fill": "#151515",
                                "colorLinkGroup": False,
                                "draggable": False,
                                "rotatable": False,
                                "resizable": False,
                                "removable": False,
                                "flipX": False,
                                "flipY": False,
                                "zChangeable": False,
                                "scaleX": 0.98,
                                "scaleY": 0.98,
                                "uniScalingUnlockable": False,
                                "angle": 0,
                                "price": 0,
                                "autoCenter": False,
                                "replaceInAllViews": False,
                                "autoSelect": False,
                                "topped": False,
                                "boundingBoxMode": "0",
                                "opacity": 1,
                                "excludeFromExport": False,
                                "locked": False,
                                "showInColorSelection": False,
                                "boundingBox": "",
                                "fixed": False,
                                "resizeToW": "0",
                                "resizeToH": "0",
                                "scaleMode": "0",
                                "minScaleLimit": 0.01,
                                "advancedEditing": False,
                                "uploadZone": False,
                                "uploadZoneMovable": False,
                                "uploadZoneRemovable": False,
                                "pattern": "",
                                "customAdds": [],
                                "colors": "#FFFFFF,#0A0A0A,#232323,#555555,#B2B2B2,#CDCDCD,#412623,#4E1616,#800707,#BA0909,#D55108,#E88014,#E29717,#FDC300,#FFED00,#646702,#042E21,#05462B,#026C27,#489A29,#A4CB16,#191F28,#172339,#0A376E,#005A96,#08A1BB,#8DEAF4,#08ADB1,#3DD684,#92EFBD,#234955,#2E2846,#402E54,#736D88,#BDB7CF,#56182F,#761133,#A60E32,#D83636,#F591A7,#F2C5AD,#F8E9E8,#381F0E,#583116,#AA650F,#6F3827,#C7932E"
                            }
                        },
                        {
                            "title": "Color 5",
                            "source": "https://jersix.com/en/wp-content/uploads/2022/08/levels-kit-evolution-c2.png",
                            "type": "image",
                            "parameters": {
                                "left": 700,
                                "top": 600,
                                "originX": "center",
                                "originY": "center",
                                "z": -1,
                                "fill": "#c00d0d",
                                "colorLinkGroup": False,
                                "draggable": False,
                                "rotatable": False,
                                "resizable": False,
                                "removable": False,
                                "flipX": False,
                                "flipY": False,
                                "zChangeable": False,
                                "scaleX": 0.98,
                                "scaleY": 0.98,
                                "uniScalingUnlockable": False,
                                "angle": 0,
                                "price": 0,
                                "autoCenter": False,
                                "replaceInAllViews": False,
                                "autoSelect": False,
                                "topped": False,
                                "boundingBoxMode": "0",
                                "opacity": 1,
                                "excludeFromExport": False,
                                "locked": False,
                                "showInColorSelection": False,
                                "boundingBox": "",
                                "fixed": False,
                                "resizeToW": "0",
                                "resizeToH": "0",
                                "scaleMode": "0",
                                "minScaleLimit": 0.01,
                                "advancedEditing": False,
                                "uploadZone": False,
                                "uploadZoneMovable": False,
                                "uploadZoneRemovable": False,
                                "pattern": "",
                                "customAdds": [],
                                "colors": "#FFFFFF,#0A0A0A,#232323,#555555,#B2B2B2,#CDCDCD,#412623,#4E1616,#800707,#BA0909,#D55108,#E88014,#E29717,#FDC300,#FFED00,#646702,#042E21,#05462B,#026C27,#489A29,#A4CB16,#191F28,#172339,#0A376E,#005A96,#08A1BB,#8DEAF4,#08ADB1,#3DD684,#92EFBD,#234955,#2E2846,#402E54,#736D88,#BDB7CF,#56182F,#761133,#A60E32,#D83636,#F591A7,#F2C5AD,#F8E9E8,#381F0E,#583116,#AA650F,#6F3827,#C7932E"
                            }
                        },
                        {
                            "title": "Color 6",
                            "source": "https://jersix.com/en/wp-content/uploads/2022/08/levels-kit-evolution-c4.png",
                            "type": "image",
                            "parameters": {
                                "left": 700,
                                "top": 600,
                                "originX": "center",
                                "originY": "center",
                                "z": -1,
                                "fill": "#c00d0d",
                                "colorLinkGroup": False,
                                "draggable": False,
                                "rotatable": False,
                                "resizable": False,
                                "removable": False,
                                "flipX": False,
                                "flipY": False,
                                "zChangeable": False,
                                "scaleX": 0.98,
                                "scaleY": 0.98,
                                "uniScalingUnlockable": False,
                                "angle": 0,
                                "price": 0,
                                "autoCenter": False,
                                "replaceInAllViews": False,
                                "autoSelect": False,
                                "topped": False,
                                "boundingBoxMode": "clipping",
                                "opacity": 1,
                                "excludeFromExport": False,
                                "locked": False,
                                "showInColorSelection": False,
                                "boundingBox": "",
                                "fixed": False,
                                "resizeToW": "0",
                                "resizeToH": "0",
                                "scaleMode": "fit",
                                "minScaleLimit": 0.01,
                                "advancedEditing": False,
                                "uploadZone": False,
                                "uploadZoneMovable": False,
                                "uploadZoneRemovable": False,
                                "customAdds": [],
                                "colors": "#FFFFFF,#0A0A0A,#232323,#555555,#B2B2B2,#CDCDCD,#412623,#4E1616,#800707,#BA0909,#D55108,#E88014,#E29717,#FDC300,#FFED00,#646702,#042E21,#05462B,#026C27,#489A29,#A4CB16,#191F28,#172339,#0A376E,#005A96,#08A1BB,#8DEAF4,#08ADB1,#3DD684,#92EFBD,#234955,#2E2846,#402E54,#736D88,#BDB7CF,#56182F,#761133,#A60E32,#D83636,#F591A7,#F2C5AD,#F8E9E8,#381F0E,#583116,#AA650F,#6F3827,#C7932E"
                            }
                        },
                        {
                            "title": "Color 7",
                            "source": "https://jersix.com/en/wp-content/uploads/2022/08/levels-kit-evolution-c3.png",
                            "type": "image",
                            "parameters": {
                                "left": 700,
                                "top": 600,
                                "originX": "center",
                                "originY": "center",
                                "z": -1,
                                "fill": "#151515",
                                "colorLinkGroup": False,
                                "draggable": False,
                                "rotatable": False,
                                "resizable": False,
                                "removable": False,
                                "flipX": False,
                                "flipY": False,
                                "zChangeable": False,
                                "scaleX": 0.98,
                                "scaleY": 0.98,
                                "uniScalingUnlockable": False,
                                "angle": 0,
                                "price": 0,
                                "autoCenter": False,
                                "replaceInAllViews": False,
                                "autoSelect": False,
                                "topped": False,
                                "boundingBoxMode": "clipping",
                                "opacity": 1,
                                "excludeFromExport": False,
                                "locked": False,
                                "showInColorSelection": False,
                                "boundingBox": "",
                                "fixed": False,
                                "resizeToW": "0",
                                "resizeToH": "0",
                                "scaleMode": "fit",
                                "minScaleLimit": 0.01,
                                "advancedEditing": False,
                                "uploadZone": False,
                                "uploadZoneMovable": False,
                                "uploadZoneRemovable": False,
                                "customAdds": [],
                                "colors": "#FFFFFF,#0A0A0A,#232323,#555555,#B2B2B2,#CDCDCD,#412623,#4E1616,#800707,#BA0909,#D55108,#E88014,#E29717,#FDC300,#FFED00,#646702,#042E21,#05462B,#026C27,#489A29,#A4CB16,#191F28,#172339,#0A376E,#005A96,#08A1BB,#8DEAF4,#08ADB1,#3DD684,#92EFBD,#234955,#2E2846,#402E54,#736D88,#BDB7CF,#56182F,#761133,#A60E32,#D83636,#F591A7,#F2C5AD,#F8E9E8,#381F0E,#583116,#AA650F,#6F3827,#C7932E"
                            }
                        },
                        {
                            "title": "Collar",
                            "source": "https://jersix.com/en/wp-content/uploads/2022/06/kit-ev-m-COLLAR.png",
                            "type": "image",
                            "parameters": {
                                "left": 700,
                                "top": 600,
                                "originX": "center",
                                "originY": "center",
                                "z": -1,
                                "fill": "#151515",
                                "colorLinkGroup": False,
                                "draggable": False,
                                "rotatable": False,
                                "resizable": False,
                                "removable": False,
                                "flipX": False,
                                "flipY": False,
                                "zChangeable": False,
                                "scaleX": 0.98,
                                "scaleY": 0.98,
                                "uniScalingUnlockable": False,
                                "angle": 0,
                                "price": 0,
                                "autoCenter": False,
                                "replaceInAllViews": False,
                                "autoSelect": False,
                                "topped": False,
                                "boundingBoxMode": "0",
                                "opacity": 1,
                                "excludeFromExport": False,
                                "locked": False,
                                "showInColorSelection": False,
                                "boundingBox": "",
                                "fixed": False,
                                "resizeToW": "0",
                                "resizeToH": "0",
                                "scaleMode": "0",
                                "minScaleLimit": 0.01,
                                "advancedEditing": False,
                                "uploadZone": False,
                                "uploadZoneMovable": False,
                                "uploadZoneRemovable": False,
                                "pattern": "",
                                "customAdds": [],
                                "colors": "#FFFFFF,#0A0A0A,#232323,#555555,#B2B2B2,#CDCDCD,#412623,#4E1616,#800707,#BA0909,#D55108,#E88014,#E29717,#FDC300,#FFED00,#646702,#042E21,#05462B,#026C27,#489A29,#A4CB16,#191F28,#172339,#0A376E,#005A96,#08A1BB,#8DEAF4,#08ADB1,#3DD684,#92EFBD,#234955,#2E2846,#402E54,#736D88,#BDB7CF,#56182F,#761133,#A60E32,#D83636,#F591A7,#F2C5AD,#F8E9E8,#381F0E,#583116,#AA650F,#6F3827,#C7932E"
                            }
                        },
                        {
                            "title": "Socks",
                            "source": "https://jersix.com/en/wp-content/uploads/2022/06/kit-ev-m-SOCKS.png",
                            "type": "image",
                            "parameters": {
                                "left": 700,
                                "top": 600,
                                "originX": "center",
                                "originY": "center",
                                "z": -1,
                                "fill": "#151515",
                                "colorLinkGroup": False,
                                "draggable": False,
                                "rotatable": False,
                                "resizable": False,
                                "removable": False,
                                "flipX": False,
                                "flipY": False,
                                "zChangeable": False,
                                "scaleX": 0.98,
                                "scaleY": 0.98,
                                "uniScalingUnlockable": False,
                                "angle": 0,
                                "price": 0,
                                "autoCenter": False,
                                "replaceInAllViews": False,
                                "autoSelect": False,
                                "topped": False,
                                "boundingBoxMode": "0",
                                "opacity": 1,
                                "excludeFromExport": False,
                                "locked": False,
                                "showInColorSelection": False,
                                "boundingBox": "",
                                "fixed": False,
                                "resizeToW": "0",
                                "resizeToH": "0",
                                "scaleMode": "0",
                                "minScaleLimit": 0.01,
                                "advancedEditing": False,
                                "uploadZone": False,
                                "uploadZoneMovable": False,
                                "uploadZoneRemovable": False,
                                "pattern": "",
                                "customAdds": [],
                                "colors": "#FFFFFF,#000000,#FFC13F,#F07339,#DE2631,#3654A3,#232048,#348549,#671E2A,#654691,#96BFE3"
                            }
                        },
                        {
                            "title": "Borders",
                            "source": "https://jersix.com/en/wp-content/uploads/2022/06/kit-ev-m-BORDERS.png",
                            "type": "image",
                            "parameters": {
                                "left": 700,
                                "top": 600,
                                "originX": "center",
                                "originY": "center",
                                "z": -1,
                                "fill": "#151515",
                                "colorLinkGroup": False,
                                "draggable": False,
                                "rotatable": False,
                                "resizable": False,
                                "removable": False,
                                "flipX": False,
                                "flipY": False,
                                "zChangeable": False,
                                "scaleX": 0.98,
                                "scaleY": 0.98,
                                "uniScalingUnlockable": False,
                                "angle": 0,
                                "price": 0,
                                "autoCenter": False,
                                "replaceInAllViews": False,
                                "autoSelect": False,
                                "topped": False,
                                "boundingBoxMode": "clipping",
                                "opacity": 1,
                                "excludeFromExport": False,
                                "locked": False,
                                "showInColorSelection": False,
                                "boundingBox": "",
                                "fixed": False,
                                "resizeToW": "0",
                                "resizeToH": "0",
                                "scaleMode": "fit",
                                "minScaleLimit": 0.01,
                                "advancedEditing": False,
                                "uploadZone": False,
                                "uploadZoneMovable": False,
                                "uploadZoneRemovable": False,
                                "pattern": "",
                                "customAdds": [],
                                "colors": "#FFFFFF,#000000,#0A1E45"
                            }
                        },
                        {
                            "title": "Jersix Logo (Chest)",
                            "source": "https://jersix.com/en/wp-content/uploads/2021/01/jersix-logo-orizzontale-left-aa.png",
                            "type": "image",
                            "parameters": {
                                "left": 445.48698253413,
                                "top": 203,
                                "originX": "center",
                                "originY": "center",
                                "z": -1,
                                "fill": "#151515",
                                "colorLinkGroup": False,
                                "draggable": False,
                                "rotatable": False,
                                "resizable": False,
                                "removable": False,
                                "flipX": False,
                                "flipY": False,
                                "zChangeable": False,
                                "scaleX": 0.35871710526316,
                                "scaleY": 0.35871710526316,
                                "uniScalingUnlockable": False,
                                "angle": 0,
                                "price": 0,
                                "autoCenter": False,
                                "replaceInAllViews": False,
                                "autoSelect": False,
                                "topped": False,
                                "boundingBoxMode": "clipping",
                                "opacity": 1,
                                "excludeFromExport": False,
                                "locked": False,
                                "showInColorSelection": False,
                                "boundingBox": "",
                                "fixed": False,
                                "resizeToW": "0",
                                "resizeToH": "0",
                                "scaleMode": "fit",
                                "minScaleLimit": 0.01,
                                "advancedEditing": False,
                                "uploadZone": False,
                                "uploadZoneMovable": False,
                                "uploadZoneRemovable": False,
                                "pattern": "",
                                "customAdds": [],
                                "colors": "#FFFFFF,#0A0A0A,#232323,#555555,#B2B2B2,#CDCDCD,#412623,#4E1616,#800707,#BA0909,#D55108,#E88014,#E29717,#FDC300,#FFED00,#646702,#042E21,#05462B,#026C27,#489A29,#A4CB16,#191F28,#172339,#0A376E,#005A96,#08A1BB,#8DEAF4,#08ADB1,#3DD684,#92EFBD,#234955,#2E2846,#402E54,#736D88,#BDB7CF,#56182F,#761133,#A60E32,#D83636,#F591A7,#F2C5AD,#F8E9E8,#381F0E,#583116,#AA650F,#6F3827,#C7932E"
                            }
                        },
                        {
                            "title": "Jersix Logo (Shorts)",
                            "source": "https://jersix.com/en/wp-content/uploads/2020/11/jersix-pittogramma-1.png",
                            "type": "image",
                            "parameters": {
                                "left": 407.70874015445,
                                "top": 707.5464785036,
                                "originX": "center",
                                "originY": "center",
                                "z": -1,
                                "fill": "#151515",
                                "colorLinkGroup": False,
                                "draggable": False,
                                "rotatable": False,
                                "resizable": False,
                                "removable": False,
                                "flipX": False,
                                "flipY": False,
                                "zChangeable": False,
                                "scaleX": 0.039893617021277,
                                "scaleY": 0.039893617021277,
                                "uniScalingUnlockable": False,
                                "angle": 3,
                                "price": 0,
                                "autoCenter": False,
                                "replaceInAllViews": False,
                                "autoSelect": False,
                                "topped": False,
                                "boundingBoxMode": "clipping",
                                "opacity": 1,
                                "excludeFromExport": False,
                                "locked": False,
                                "showInColorSelection": False,
                                "boundingBox": "",
                                "fixed": False,
                                "resizeToW": "0",
                                "resizeToH": "0",
                                "scaleMode": "fit",
                                "minScaleLimit": 0.01,
                                "advancedEditing": False,
                                "uploadZone": False,
                                "uploadZoneMovable": False,
                                "uploadZoneRemovable": False,
                                "customAdds": [],
                                "colors": "#FFFFFF,#0A0A0A,#232323,#555555,#B2B2B2,#CDCDCD,#412623,#4E1616,#800707,#BA0909,#D55108,#E88014,#E29717,#FDC300,#FFED00,#646702,#042E21,#05462B,#026C27,#489A29,#A4CB16,#191F28,#172339,#0A376E,#005A96,#08A1BB,#8DEAF4,#08ADB1,#3DD684,#92EFBD,#234955,#2E2846,#402E54,#736D88,#BDB7CF,#56182F,#761133,#A60E32,#D83636,#F591A7,#F2C5AD,#F8E9E8,#381F0E,#583116,#AA650F,#6F3827,#C7932E"
                            }
                        },
                        {
                            "title": "Jersix Logo (Back)",
                            "source": "https://jersix.com/en/wp-content/uploads/2020/11/jersix-pittogramma-1.png",
                            "type": "image",
                            "parameters": {
                                "left": 897,
                                "top": 169,
                                "originX": "center",
                                "originY": "center",
                                "z": -1,
                                "fill": "#151515",
                                "colorLinkGroup": False,
                                "draggable": False,
                                "rotatable": False,
                                "resizable": False,
                                "removable": False,
                                "flipX": False,
                                "flipY": False,
                                "zChangeable": False,
                                "scaleX": 0.017391123670213,
                                "scaleY": 0.017391123670213,
                                "uniScalingUnlockable": False,
                                "angle": 0,
                                "price": 0,
                                "autoCenter": False,
                                "replaceInAllViews": False,
                                "autoSelect": False,
                                "topped": False,
                                "boundingBoxMode": "clipping",
                                "opacity": 1,
                                "excludeFromExport": False,
                                "locked": False,
                                "showInColorSelection": False,
                                "boundingBox": "",
                                "fixed": False,
                                "resizeToW": "0",
                                "resizeToH": "0",
                                "scaleMode": "fit",
                                "minScaleLimit": 0.01,
                                "advancedEditing": False,
                                "uploadZone": False,
                                "uploadZoneMovable": False,
                                "uploadZoneRemovable": False,
                                "pattern": "",
                                "customAdds": [],
                                "colors": "#FFFFFF,#0A0A0A,#232323,#555555,#B2B2B2,#CDCDCD,#412623,#4E1616,#800707,#BA0909,#D55108,#E88014,#E29717,#FDC300,#FFED00,#646702,#042E21,#05462B,#026C27,#489A29,#A4CB16,#191F28,#172339,#0A376E,#005A96,#08A1BB,#8DEAF4,#08ADB1,#3DD684,#92EFBD,#234955,#2E2846,#402E54,#736D88,#BDB7CF,#56182F,#761133,#A60E32,#D83636,#F591A7,#F2C5AD,#F8E9E8,#381F0E,#583116,#AA650F,#6F3827,#C7932E"
                            }
                        },
                        {
                            "title": "Name",
                            "source": "PLAYER",
                            "type": "text",
                            "parameters": {
                                "left": 897,
                                "top": 215.03565789474,
                                "originX": "center",
                                "originY": "center",
                                "z": -1,
                                "fill": "#151515",
                                "colorLinkGroup": False,
                                "draggable": False,
                                "rotatable": False,
                                "resizable": False,
                                "removable": False,
                                "flipX": False,
                                "flipY": False,
                                "zChangeable": False,
                                "scaleX": 1,
                                "scaleY": 1,
                                "uniScalingUnlockable": False,
                                "angle": 0,
                                "price": 0,
                                "autoCenter": False,
                                "replaceInAllViews": False,
                                "autoSelect": False,
                                "topped": False,
                                "boundingBoxMode": "clipping",
                                "opacity": 1,
                                "excludeFromExport": False,
                                "locked": False,
                                "showInColorSelection": False,
                                "boundingBox": "",
                                "fixed": False,
                                "fontFamily": "Roddenberry",
                                "fontSize": 34,
                                "editable": True,
                                "lineHeight": 1,
                                "textDecoration": "normal",
                                "maxLength": 0,
                                "fontWeight": "normal",
                                "fontStyle": "normal",
                                "textAlign": "left",
                                "curvable": False,
                                "curved": False,
                                "curveSpacing": 10,
                                "curveRadius": 80,
                                "curveReverse": False,
                                "stroke": "#ffffff",
                                "strokeWidth": 0,
                                "maxLines": 1,
                                "letterSpacing": 0,
                                "chargeAfterEditing": False,
                                "minFontSize": 1,
                                "maxFontSize": 1000,
                                "textTransform": "none",
                                "widthFontSize": 0,
                                "textBox": False,
                                "shadowBlur": 0,
                                "shadowOffsetX": 0,
                                "shadowOffsetY": 0,
                                "textPlaceholder": True,
                                "pattern": "",
                                "colors": "#FFFFFF,#0A0A0A,#232323,#555555,#B2B2B2,#CDCDCD,#412623,#4E1616,#800707,#BA0909,#D55108,#E88014,#E29717,#FDC300,#FFED00,#646702,#042E21,#05462B,#026C27,#489A29,#A4CB16,#191F28,#172339,#0A376E,#005A96,#08A1BB,#8DEAF4,#08ADB1,#3DD684,#92EFBD,#234955,#2E2846,#402E54,#736D88,#BDB7CF,#56182F,#761133,#A60E32,#D83636,#F591A7,#F2C5AD,#F8E9E8,#381F0E,#583116,#AA650F,#6F3827,#C7932E"
                            }
                        },
                        {
                            "title": "Number (Back)",
                            "source": "00",
                            "type": "text",
                            "parameters": {
                                "left": 904,
                                "top": 335,
                                "originX": "center",
                                "originY": "center",
                                "z": -1,
                                "fill": "#151515",
                                "colorLinkGroup": False,
                                "draggable": False,
                                "rotatable": False,
                                "resizable": False,
                                "removable": False,
                                "flipX": False,
                                "flipY": False,
                                "zChangeable": False,
                                "scaleX": 1,
                                "scaleY": 1,
                                "uniScalingUnlockable": False,
                                "angle": 0,
                                "price": 0,
                                "autoCenter": False,
                                "replaceInAllViews": False,
                                "autoSelect": False,
                                "topped": False,
                                "boundingBoxMode": "clipping",
                                "opacity": 1,
                                "excludeFromExport": False,
                                "locked": False,
                                "showInColorSelection": False,
                                "boundingBox": "",
                                "fixed": False,
                                "fontFamily": "Roddenberry",
                                "fontSize": 180,
                                "editable": True,
                                "lineHeight": 1,
                                "textDecoration": "normal",
                                "maxLength": 0,
                                "fontWeight": "normal",
                                "fontStyle": "normal",
                                "textAlign": "left",
                                "curvable": False,
                                "curved": False,
                                "curveSpacing": 10,
                                "curveRadius": 80,
                                "curveReverse": False,
                                "stroke": "#ffffff",
                                "strokeWidth": 0,
                                "maxLines": 1,
                                "letterSpacing": 0,
                                "chargeAfterEditing": False,
                                "minFontSize": 1,
                                "maxFontSize": 1000,
                                "textTransform": "none",
                                "widthFontSize": 0,
                                "textBox": False,
                                "shadowBlur": 0,
                                "shadowOffsetX": 0,
                                "shadowOffsetY": 0,
                                "numberPlaceholder": True,
                                "textLinkGroup": "number",
                                "colors": "#FFFFFF,#0A0A0A,#232323,#555555,#B2B2B2,#CDCDCD,#412623,#4E1616,#800707,#BA0909,#D55108,#E88014,#E29717,#FDC300,#FFED00,#646702,#042E21,#05462B,#026C27,#489A29,#A4CB16,#191F28,#172339,#0A376E,#005A96,#08A1BB,#8DEAF4,#08ADB1,#3DD684,#92EFBD,#234955,#2E2846,#402E54,#736D88,#BDB7CF,#56182F,#761133,#A60E32,#D83636,#F591A7,#F2C5AD,#F8E9E8,#381F0E,#583116,#AA650F,#6F3827,#C7932E"
                            }
                        },
                        {
                            "title": "Number (Shorts)",
                            "source": "00",
                            "type": "text",
                            "parameters": {
                                "left": 585,
                                "top": 709,
                                "originX": "center",
                                "originY": "center",
                                "z": -1,
                                "fill": "#151515",
                                "colorLinkGroup": False,
                                "draggable": False,
                                "rotatable": False,
                                "resizable": False,
                                "removable": False,
                                "flipX": False,
                                "flipY": False,
                                "zChangeable": False,
                                "scaleX": 1,
                                "scaleY": 1,
                                "uniScalingUnlockable": False,
                                "angle": 356,
                                "price": 0,
                                "autoCenter": False,
                                "replaceInAllViews": False,
                                "autoSelect": False,
                                "topped": False,
                                "boundingBoxMode": "clipping",
                                "opacity": 1,
                                "excludeFromExport": False,
                                "locked": False,
                                "showInColorSelection": False,
                                "boundingBox": "",
                                "fixed": False,
                                "fontFamily": "Roddenberry",
                                "fontSize": 60,
                                "editable": True,
                                "lineHeight": 1,
                                "textDecoration": "normal",
                                "maxLength": 0,
                                "fontWeight": "normal",
                                "fontStyle": "normal",
                                "textAlign": "left",
                                "curvable": False,
                                "curved": False,
                                "curveSpacing": 10,
                                "curveRadius": 80,
                                "curveReverse": False,
                                "strokeWidth": 0,
                                "maxLines": 1,
                                "letterSpacing": 0,
                                "chargeAfterEditing": False,
                                "minFontSize": 1,
                                "maxFontSize": 1000,
                                "textTransform": "none",
                                "widthFontSize": 0,
                                "textBox": False,
                                "shadowBlur": 0,
                                "shadowOffsetX": 0,
                                "shadowOffsetY": 0,
                                "numberPlaceholder": True,
                                "textLinkGroup": "number",
                                "colors": "#FFFFFF,#0A0A0A,#232323,#555555,#B2B2B2,#CDCDCD,#412623,#4E1616,#800707,#BA0909,#D55108,#E88014,#E29717,#FDC300,#FFED00,#646702,#042E21,#05462B,#026C27,#489A29,#A4CB16,#191F28,#172339,#0A376E,#005A96,#08A1BB,#8DEAF4,#08ADB1,#3DD684,#92EFBD,#234955,#2E2846,#402E54,#736D88,#BDB7CF,#56182F,#761133,#A60E32,#D83636,#F591A7,#F2C5AD,#F8E9E8,#381F0E,#583116,#AA650F,#6F3827,#C7932E"
                            }
                        },
                        {
                            "title": "Shadow",
                            "source": "https://jersix.com/en/wp-content/uploads/2022/06/kit-ev-m-SHAD.png",
                            "type": "image",
                            "parameters": {
                                "left": 700,
                                "top": 600,
                                "originX": "center",
                                "originY": "center",
                                "z": -1,
                                "fill": False,
                                "colorLinkGroup": False,
                                "draggable": False,
                                "rotatable": False,
                                "resizable": False,
                                "removable": False,
                                "flipX": False,
                                "flipY": False,
                                "zChangeable": False,
                                "scaleX": 0.98,
                                "scaleY": 0.98,
                                "uniScalingUnlockable": False,
                                "angle": 0,
                                "price": 0,
                                "autoCenter": False,
                                "replaceInAllViews": False,
                                "autoSelect": False,
                                "topped": True,
                                "boundingBoxMode": "0",
                                "opacity": 1,
                                "excludeFromExport": False,
                                "locked": True,
                                "showInColorSelection": False,
                                "boundingBox": "",
                                "fixed": False,
                                "resizeToW": "0",
                                "resizeToH": "0",
                                "scaleMode": "0",
                                "minScaleLimit": 0.01,
                                "advancedEditing": False,
                                "uploadZone": False,
                                "uploadZoneMovable": False,
                                "uploadZoneRemovable": False,
                                "pattern": "",
                                "customAdds": []
                            }
                        }
                    ]
                }

if __name__ == "__main__":
    main()
